title: OKTW Network
description: 由許多人聯合經營的Minecraft伺服器
keywords: OKTW,Minecraft,伺服器,Kotlin,Galaxy,星系計畫

baseurl: "" 
url: "https://mc.oktw.one" 

languages: ["tw","en"]
exclude_from_localizations: ["javascript", "images", "css"]

github_username:  OKTW-Network
repository: OKTW-Network/oktw-network.github.io

collections:
  wikiPages:
    categories: true
    order: true
    title: true
    description: true
    icon: true
    permalink: /wiki/:name
    output: true

lsi: false
safe: true
incremental: false
highlighter: rouge

markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-multiple-languages-plugin
  - jekyll-sass-converter
  - jekyll-sitemap
  - jekyll-include-cache

gist:
  noscript: false

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

theme: jekyll-theme-slate